# Generated by Django 5.0.6 on 2024-07-05 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 15, 30, 4, 455324, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
