# Generated by Django 5.0.6 on 2024-07-05 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score'),
        ),
    ]
